[package]
name = "enumacro"
version = "0.1.0"
authors = ["Luca Pizzamiglio <pizzamig@FreeBSD.org>"]
edition = "2018"

[dependencies]
enumacro-derive = { path = "enumacro-derive", version = "=0.1.0" }
